[package]
name = "snowbridge-outbound-router-primitives"
description = "Snowbridge Router Primitives"
version = "0.9.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition.workspace = true
repository.workspace = true
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
log = { workspace = true }

frame-support = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

xcm = { workspace = true }
xcm-executor = { workspace = true }
xcm-builder = { workspace = true }

snowbridge-core = { workspace = true }
snowbridge-outbound-primitives = { workspace = true }

hex-literal = { workspace = true, default-features = true }

[dev-dependencies]

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"log/std",
	"scale-info/std",
	"snowbridge-core/std",
	"snowbridge-outbound-primitives/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
