[package]
name = "snowbridge-outbound-primitives"
description = "Snowbridge outbound primitives"
version = "0.2.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition.workspace = true
repository.workspace = true
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
hex-literal = { workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true }

polkadot-parachain-primitives = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }

alloy-core = { workspace = true, features = ["sol-types"] }
ethabi = { workspace = true }

snowbridge-core = { workspace = true }
snowbridge-verification-primitives = { workspace = true }

[dev-dependencies]
hex = { workspace = true, default-features = true }
xcm-executor = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
    "alloy-core/std",
    "codec/std",
    "ethabi/std",
    "frame-support/std",
    "frame-system/std",
    "polkadot-parachain-primitives/std",
    "scale-info/std",
    "snowbridge-core/std",
    "snowbridge-verification-primitives/std",
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-std/std",
    "xcm-builder/std",
    "xcm/std",
]
